"""Backend service package."""

from backend.services.manual_memo_generator import (
    CompanyMetadata,
    InvalidMemoEvidenceError,
    InvalidMemoJSONError,
    InvalidMemoSchemaError,
    ManualMemoGenerationError,
    ManualMemoGenerator,
    ManualMemoLLM,
    ManualMemoRequest,
    ManualSourceExcerpt,
    REASONING_CHAIN,
    build_manual_memo_prompt,
    parse_investment_memo_response,
    source_documents_from_request,
)
from backend.services.memo_quality_gate import (
    MAXIMUM_PHASE_3_REVIEW_COUNT,
    MINIMUM_AVERAGE_SCORE,
    MINIMUM_CRITERION_SCORE,
    MINIMUM_PHASE_3_REVIEW_COUNT,
    MemoQualityGateResult,
    PHASE_3_RUBRIC,
    Phase3MemoQualityGateResult,
    QUALITATIVE_ONLY_CRITERIA_UNTIL_PHASE_4,
    evaluate_memo_quality_gate,
    evaluate_single_memo_quality_review,
)

__all__ = [
    "CompanyMetadata",
    "InvalidMemoEvidenceError",
    "InvalidMemoJSONError",
    "InvalidMemoSchemaError",
    "ManualMemoGenerationError",
    "ManualMemoGenerator",
    "ManualMemoLLM",
    "ManualMemoRequest",
    "ManualSourceExcerpt",
    "MAXIMUM_PHASE_3_REVIEW_COUNT",
    "MemoQualityGateResult",
    "MINIMUM_AVERAGE_SCORE",
    "MINIMUM_CRITERION_SCORE",
    "MINIMUM_PHASE_3_REVIEW_COUNT",
    "PHASE_3_RUBRIC",
    "Phase3MemoQualityGateResult",
    "QUALITATIVE_ONLY_CRITERIA_UNTIL_PHASE_4",
    "REASONING_CHAIN",
    "build_manual_memo_prompt",
    "evaluate_memo_quality_gate",
    "evaluate_single_memo_quality_review",
    "parse_investment_memo_response",
    "source_documents_from_request",
]
